apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      serviceAccountName: kube-state-metrics
      containers:
      - name: kube-state-metrics
        image: private.registry.com/k8s.gcr.io/kube-state-metrics:v1.4.0
        ports:
        - containerPort: 8080
